spring:
  profiles:
    active:
    - dev
---

spring:
  profiles: dev
  application: 
    name: microservicecloud-config-client-liujiedong
---

spring:
  profiles: test
  application: 
    name: microservicecloud-config-client-test